version: '3'

services:

  mongo1:
    image: mongo:latest
    container_name: mongo1
    restart: always
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    image: mongo:latest
    container_name: mongo2
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo3:
    image: mongo:latest
    container_name: mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: >
      sh -c "
        sleep 30 &&
        mongo --host mongo1:27017 --eval 'rs.initiate({
          _id: \"rs0\",
          members: [
            {_id: 0, host: \"mongo1:27017\"},
            {_id: 1, host: \"mongo2:27017\"},
            {_id: 2, host: \"mongo3:27017\"}
          ]
        })'"

  mq:
    image: rabbitmq:3-management-alpine
    container_name: scrabble_mq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ~/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/rabbitmq/log/:/var/log/rabbitmq
    restart: always